pools:
  - id: HTTP pool
    gun:
      type: http
      target: localhost:8000
      ssl: false
    ammo:
      type: uri
      file: ./ammo.txt
    result:
      type: phout
      destination: ./phout.log
    rps:
      - duration: 10s
        type: line
        from: 10
        to: 100
      - duration: 20s
        type: const
        ops: 100
      - duration: 10s
        type: line
        from: 100
        to: 10
    startup:
      type: once
      times: 100
log:
  level: info
monitoring:
  expvar:
    enabled: true
    port: 1234